In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
x =np.full((4, 5), 3.14)

In [8]:
np.random.random((3, 3))

array([[0.71319908, 0.73781941, 0.118524  ],
       [0.32081927, 0.61618116, 0.21377947],
       [0.13827522, 0.76276421, 0.48918417]])

In [9]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# accedé a un element d'une matrice

In [14]:
x [0,1]

3.14

In [21]:
x[2,4]=12

In [22]:
x

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14, 12.  ],
       [ 3.14,  3.14,  3.14, 12.  , 12.  ]])

12.0 car tout les element son du meme tyoe

In [30]:
x2 = np.random.randint(10, 13, size=(3, 4)) 

In [35]:
x2

array([[10, 11, 10, 11],
       [11, 10, 11, 10],
       [11, 11, 10, 12]])

To extract a contiguous subset of a string, you can combine []  and : to access several elements at once. This is called slicing. The syntax is simple :  x[begin:end:step]. 

In [37]:
x2

array([[10, 11, 10, 11],
       [11, 10, 11, 10],
       [11, 11, 10, 12]])

In [38]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [39]:
np.concatenate([y,x])

array([3, 2, 1, 1, 2, 3])

In [40]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [42]:
x = [-2, -1, 1, 2]

print("Absolute value: ", np.abs(x))
print("Exponential: ", np.exp(x))
print("Logarithm: ", np.log(np.abs(x)))

Absolute value:  [2 1 1 2]
Exponential:  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithm:  [0.69314718 0.         0.         0.69314718]
